### ISSUE TITLE
Issue with Usage of TM 

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#10]
@MinMah23 

1. If your TM reference to IM and it do not use TM directly, you should have to use "derivation of..." module. For example, your TM1 reference by the IM2. However, I don't see any direct use there. 

2. Also, in your some of the source links, I saw that those are not correct/ I don't find relevant information from that source link. For example, in TM2, Newton’s Second Law for Rotation is not available on the given source link.

**Comment by MinMah23** [comment]
- I've added "derivation of" section in commit 4d129a5.
- I've checked the source parts.
