### ISSUE TITLE
Issue with design 

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#11]
@MinMah23  

In DD3, the link is not properly formed inside the table and it looks weird.

Datatypes are null? 

IM?? in IM1 should be reference properly.

**Comment by MinMah23** [comment]
@DeeshaPatel 
DD3?
The source link is a bit long, but as I checked it works.
Data Types are empty and I kept it on the document to make sure that I don't need it and then delete it in commit fb2642a. 
Yeah, you're right, I corrected it.
