### ISSUE TITLE
Development plan 

### ISSUE THREAD

**Issue by Maryamvalian** [MinMah23/CAS741-Project#17]
@MinMah23 Development plan is not necessary but if you do not add any text in this section, I think you should delete the section title.

**Comment by smiths** [comment]
For a section of a template, if you don't use it, keep the title and enter "Not applicable".  If it isn't obvious, explain why the section is not applicable.  I don't think I explicitly mentioned this in class, but with a standard template you don't want to delete sections.  If someone reads the document and a section is missing, they don't know if the author forgot the section, or intentionally removed it.

**Comment by MinMah23** [comment]
I will write Not Applicable.
