### ISSUE TITLE
SRS file

### ISSUE THREAD

**Issue by MinMah23** [MinMah23/CAS741-Project#2]
@maryamvalian and @DeeshaPatel 
My [SRS](https://github.com/MinMah23/CAS741-Project/blob/main/docs/SRS/SRS.pdf) is ready to be reviewed, I am totally open to your comments and ideas. Thank you in advance for you time and attention.
Dear Prof. @smiths Thank you for extending the submission deadline for me.

**Comment by smiths** [comment]
Thank you @MinMah23.  I'll get to the review as soon as I can.

**Comment by smiths** [comment]
I've provided a marked-up version of the SRS in 8d6c734 with my review comments.
