### ISSUE TITLE
VnV Plan review: Common comments

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#23]
- [x]  In your first page, it seems that you used title "ID Simulator" which is not the same as SRS document. I think it should be the same. 
- [x]  In you index pages, section 6.3 has "module ?". It should be correctly referenced.

**Comment by DeeshaPatel** [comment]
- [ ] You can remove the blank section from the VnV Plan.

**Comment by MinMah23** [comment]
1- Yes, I updated the name of the software in SRS also in 2ab4d13 commit.
2- Section 6 is related to unit test which left blank intentionally until the design, I clear this part in commit a3ea25e.
