### ISSUE TITLE
VnV Plan review: Section 3.3 and 4.5 

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#25]
In section 3.3 Relevant Document (Page no: 1), 

- [x] You can add MIS too for relevant document. 

In section 4.5 Implementation Verification plan (Page no: 2), 

- [x]  You can give detailed description of "how code walkthrough will be carried out?"

**Comment by MinMah23** [comment]
Added to the document in commit a3ea25e.
