### ISSUE TITLE
VnV Plan review: Functional requirement

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#26]
- [x] In section 5,  Introduction part, you can mention particularly which section are you referring for functional requirement in SRS document
- [x] You should use Camel case for the name of the test case. 
- [x] Second functional test case: you just wrote the "error message" for "output". Here, you can give more details about the error. 
- [x] In table 2, it seems that there is no table "**line before TC**" and there is a "**line after error message**", which looks weird. 
- [x] Also, you can describe error in output part of the particular test case, so your table size would be reduced and more manageable.

**Comment by DeeshaPatel** [comment]
- [x]  There is no space between "Section5". It should be "Section 5" in 5.1.2
- [x] Test case derivation is continue to the output for test case 1 in 5.1.2

**Comment by MinMah23** [comment]
Updated in commit 7ce5de1.
