### ISSUE TITLE
Problem with testing accuracy

### ISSUE THREAD

**Issue by MinMah23** [MinMah23/CAS741-Project#28]
In #27 and last comment, it was mentioned the problem with accuracy testing of my problem. Here is the problem, I do not have any experimental data to test it, I've searched but most the studies work on the data related to stabilizing the inverted pendulum but I need to simulate it, I want to check my result with program which written in another language (MATLAB) by somebody else that I found on the Internet. Is it acceptable? If not, what should I do?

**Comment by smiths** [comment]
Yes, you can do what you propose @MinMah23.  What you are proposing is what I called a pseudo-oracle during my presentation on VnV.
