### ISSUE TITLE
Related to Symbols

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#3]
@MinMah23 

I found some issues with the 1.2 Table of Symbols (page iv). The weight of the things are not much important but it should be corrected. 
-  There are some missing Symbols that you have used (For example, r is not there for radius) 
- I don't find uniformity of the symbols. (For example, you mentioned about m in the TM and you specified m_p in the Symbol table)
- If you used m for mass in your document, then why used same thing with different objects (I mean m_c for Mass of Cart and M_p for Mass of Cart.... Both should be capital or Both should be lower case)

**Comment by MinMah23** [comment]
@DeeshaPatel 
Dear Deesha, Thank you so much for your time and consideration. You made a precise review which helps me a lot.
About the comments:
- I have corrected missing symbols and I will check them all.
- about the second and third ones, yeah, you are right, I wanted to make distinct between them but all of "m" are used to describe mass, so I unified all of them to "m".

**Comment by MinMah23** [comment]
I've done the corrects in commit fb2642a, so I close this issue.
