### ISSUE TITLE
VnV plan

### ISSUE THREAD

**Issue by KarenKarenWang** [MinMah23/CAS741-Project#31]
So sorry for late review,
The document follows a clear structure and includes all the necessary sections for a V&V plan.
In the Objectives section, it is better to clarify what is meant by "adequate usability". Also, it may be useful to include some metrics or criteria for verifying and validating the final product.

**Comment by KarenKarenWang** [comment]
One potential area for improvement could be to provide more cases about the valid input that will return a valid output.

**Comment by KarenKarenWang** [comment]
Maybe better to set links in between the context like" FR1 and FR2 of requirements in **section5** of the SRS."

**Comment by KarenKarenWang** [comment]
Automated Testing and Verification Tools: It's good that multiple tools will be used for automated testing and code analysis. It might be worth mentioning whether any custom tools or scripts will be used and who will be responsible for maintaining the automated testing infrastructure.

**Comment by KarenKarenWang** [comment]
Overall, the plan seems well-organized and covers most of the necessary steps for verification and testing.

**Comment by MinMah23** [comment]
Thank you.
