### ISSUE TITLE
MG & MIS

### ISSUE THREAD

**Issue by MinMah23** [MinMah23/CAS741-Project#32]
Dear Prof. @smiths,
My [MG](https://github.com/MinMah23/CAS741-Project/blob/main/docs/Design/SoftArchitecture/MG.pdf) and [MIS](https://github.com/MinMah23/CAS741-Project/blob/main/docs/Design/SoftDetailedDes/MIS.pdf) is ready for review. 
Thank you for your time and valuable feedback.

**Comment by smiths** [comment]
Thank you @MinMah23.

**Comment by smiths** [comment]
My feedback on the MG and MIS is attached.

[MG.pdf](https://github.com/MinMah23/CAS741-Project/files/11205001/MG.pdf)
[MIS.pdf](https://github.com/MinMah23/CAS741-Project/files/11205005/MIS.pdf)
