### ISSUE TITLE
MG & MIs

### ISSUE THREAD

**Issue by MinMah23** [MinMah23/CAS741-Project#33]
Dear @DeeshaPatel 
My [MG](https://github.com/MinMah23/CAS741-Project/blob/main/docs/Design/SoftArchitecture/MG.pdf) and [MIS](https://github.com/MinMah23/CAS741-Project/blob/main/docs/Design/SoftDetailedDes/MIS.pdf) is ready for review. 
Thank you for your time and valuable feedback.

**Comment by DeeshaPatel** [comment]
Dear @MinMah23, I have done my review for your both documents. :)
