### ISSUE TITLE
MG & MIS

### ISSUE THREAD

**Issue by MinMah23** [MinMah23/CAS741-Project#34]
Dear @joedf,
My [MG](https://github.com/MinMah23/CAS741-Project/blob/main/docs/Design/SoftArchitecture/MG.pdf) and [MIS](https://github.com/MinMah23/CAS741-Project/blob/main/docs/Design/SoftDetailedDes/MIS.pdf) is ready for review. 
Thank you for your time and valuable feedback.

**Comment by joedf** [comment]
Done! #37 #38
