### ISSUE TITLE
Some comments for MG 

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#35]
As you don't have many issues in your document, I am simply divided it for both documents. 

- [x] 1 Anticipated changes should associated with only 1 Module in your MG. OR if you are using more than 1 modules for single anticipated changes then you need to provide clarification for that.
- [x] For your AC6, it's better to say: "The choice of data structure for different operations on data." (Remove "and"). 
- [ ] For calculating position of cart and angular position, I guess you need M2: Input parameters module. (Check your table). 
- [x] Your service for M3 is confusing. I understood it by checking your MIS. but I am sure that you can make it clear. 
- [x] Missing "Field Type" in all the modules. 
- [x] In input parameter module, last second sentence is confusing. I guess you missed the word "Constraint".

**Comment by MinMah23** [comment]
Dear @DeeshaPatel,
I appreciate your time and useful comments, I corrected some of them  in commit 70f9f3b and have question about the others as below:

1.  In your comment "For calculating position of cart and angular position, I guess you need M2: Input parameters module. (Check your table).": if you mean table2,  and R3, I think the inputs needed for calculating the outputs are in Data Structure module, if you mean something else, please  clarify it for me.
2. In "Your service for M3 is confusing. I understood it by checking your MIS. but I am sure that you can make it clear.": would you please tell me which part is ambiguous?

**Comment by DeeshaPatel** [comment]
For your first comment, I have checked your [SRS ](https://github.com/MinMah23/CAS741-Project/blob/main/docs/SRS/SRS.pdf), on page number 15, R3: which says that it is for calculating the position of the cart and angular position. However, in your [MG ](https://github.com/MinMah23/CAS741-Project/blob/main/docs/Design/SoftArchitecture/MG.pdf) document, page number 4 -> section 6 -> table 2 -> R3 is not connected with the input module (M2). Do you think, you can able to calculate the position without the input parameters?

**Comment by DeeshaPatel** [comment]
For your second comment, page number 5 -> 7.2.2 Constant Parameter Module -> Services -> First line says: "Stores all the constant values, [THIS IS PERFECT] including constant and conditions on the input/output values [IF I READ IT FOR THE FIRST TIME IT FEELS LIKE YOU ARE GOING TO STORE SOME CONDITIONS IN YOUR CONSTANT MODULE]. However, the MIS document does not contain any conditions in your Constant Parameter Module. You can say constraint values but may be the condition does not make any sense here. Hope I am clear now.

**Comment by MinMah23** [comment]
> 1. I think the inputs needed for calculating the outputs are in Data Structure module,

Thank you dear for your clarification, but I think the inputs needed for calculating the outputs are in Data Structure module, so I didn't mention the Input parameters Module.

**Comment by MinMah23** [comment]
> For your second comment, page number 5 -> 7.2.2 Constant Parameter Module -> Services -> First line says: "Stores all the constant values, [THIS IS PERFECT] including constant and conditions on the input/output values [IF I READ IT FOR THE FIRST TIME IT FEELS LIKE YOU ARE GOING TO STORE SOME CONDITIONS IN YOUR CONSTANT MODULE]. However, the MIS document does not contain any conditions in your Constant Parameter Module. You can say constraint values but may be the condition does not make any sense here. Hope I am clear now.

I got it, I correct it in 1c55b99.
Thank you so much.
