### ISSUE TITLE
Review MG - items

### ISSUE THREAD

**Issue by joedf** [MinMah23/CAS741-Project#37]
- [x] Why was table 2 moved up from the traceability section to the connection section?
- [x] I think M2 is an "Abstract Object" instead, maybe?  Yes, they both have state and behaviour, but you only have one input module, so it's more of a singleton no? unless you plan on having multiple input modules to handle different types of data entry? I think this is also the case for M4 and M6.
- [ ] for M6 (section 7.3.5); maybe service is just "Provides the main program" and the "calls the different modules in the appropriate
order" can be part of the secret? or not needed? does not add much needed knowledge...
- [x] minor suggestion, maybe simplify "The Equation of Motion ODE Module" to "Motion Equation ODE Module" ? But also, doesn't the "E" in ODE mean equation? so, maybe a bit redundant? could be even simpler "Motion ODE Module" ?

**Comment by MinMah23** [comment]
Thank you for your time and useful comments, I've update in commit 1c55b99. about the comment for section 7.3.5, I prefer to keep it.
