### ISSUE TITLE
Review MIS - items

### ISSUE THREAD

**Issue by joedf** [MinMah23/CAS741-Project#38]
- [ ] maybe remove "character | char a single symbol or digit", not used anywhere
- [x] same for "integer" and "non-negative integer"? unless I missed it somewhere?
- [ ] 6.4.3: lots of assumptions of valid input, maybe not needed. I think it's the job of the input module to check if this is respected...
- [ ] 10.4.4: I don't think you need to list all the functions there. You have mentioned the Uses modules already that have those functions, I believe...? If so, redundant and also harder to update the document in the future... 
- [x] 7.4.3: why assume this? Is this not the just of the input module to check there's a valid value everywhere used?
- I really like the exceptions table in the appendix idea! 👍

**Comment by MinMah23** [comment]
Thank you for your time and useful comments, I've updated some of them in commit 1c55b99. 
About the others:

1. Strings are sequences of characters and I used string, so I should keep "char" .
2. About 6.4.3. the assumptions are all about the format of input file, I expect the file in this order.
3. I understand what you're telling about the maintainability of the document but I prefer to keep them to clarify the flow of the program.
