### ISSUE TITLE
Acronym

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#4]
@MinMah23  

I found some less important issue with your document which is as follow: 

- You have used IP in 2.1 Purpose of Document(Page 2), and it is first use of IP. I think you should expand it when you use for the first time.

**Comment by DeeshaPatel** [comment]
Also, I found one more problem with the same section. 

2.3 Characteristics of Intended Reader section indicates in the first line that "equations of motion in Physics". 

What do you think to replace it with just "Motion in Physics"?

**Comment by MinMah23** [comment]
@DeeshaPatel 
Actually IP is an abbreviation for Inverted Pendulum which I have mentioned it at the table 1.3.
I was good at Physics when I was at high school, not at all now, but as I understood it's better to make it more specific, maybe physics dynamics can be used. 
Done in commit fb2642a.

**Comment by MinMah23** [comment]
It'done.

**Comment by smiths** [comment]
@MinMah23 it is good practice to include the commit where the work is done that closes the issue.  My guess is that in this case the commit in question is 6a51c3adecf446acb437c456afc5d89d07f23f01.  (You link the commit just by including the commit hash in the text.)

**Comment by MinMah23** [comment]
@smiths 
Thanks, I will do it for the other issues. Should I open the closed ones to add it?

**Comment by smiths** [comment]
You can add the traceability information to commits for future issues.  You don't need to do it for the ones you have already closed.  You also don't need to open an issue to add further information.  You can append comments to closed issues, just like we are doing now.  :smile:  You can also edit previous comments to include any information you later want to add.
