### ISSUE TITLE
Problem with System Context

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#5]
@MinMah23 

In Section 3.1 System Context --> The Inverted Pendulum simulation software Responsibilities: --> 

Your text is as below: 
Calculate and show the outputs.

<img width="922" alt="Screenshot 2023-02-07 at 3 10 10 PM" src="https://user-images.githubusercontent.com/25998025/217368348-a973b2b7-2ffa-42ab-b029-a54ada7f5ffd.png">

However, as per the requirement, you should specify the type of output here.

**Comment by MinMah23** [comment]
@DeeshaPatel 
I added the outputs in the commit fb2642a.
