### ISSUE TITLE
User Characteristic 

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#6]
@MinMah23 

In 3.2 User Characteristics, you mention about physics. But not specified what kind of physics User should know. Is it motion physics or whole physics terms?

**Comment by MinMah23** [comment]
@DeeshaPatel 
I think for the final user, knowing the concepts of Physics and Math which are taught in undergrad courses are enough, therefore I mentioned "The end user of the Inverted Pendulum simulation software should have an understanding of undergraduate Calculus and Physics."
