### ISSUE TITLE
In Problem Description

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#7]
@MinMah23  

In section 4.1 Problem Description (Page 3), you started the paragraph with the introduction of the system. But I guess this section should mainly focuses on the your solution toward the problem in "PROBLEM SPACE". 

<img width="988" alt="Screenshot 2023-02-07 at 3 23 55 PM" src="https://user-images.githubusercontent.com/25998025/217370188-041db829-2951-4a8b-a4a8-a5a8af994898.png">

Also, first paragraph seems like repetition of the Introduction paragraph.

**Comment by MinMah23** [comment]
@DeeshaPatel 
As I got, this section is allocated to describe the problem and focused on the part that we want to solve, the picture that you attached, also emphasizes to talk about the problem not the solution. I described my problem details at the first paragraph and then at the second paragraph, I talked about my area of solution which is describing and simulating the system. Do you think I should omit the first paragraph? so when is the right place for the problem's details?
