### ISSUE TITLE
Goals - Question 

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#8]
In section 4.1.3 Goal Statements (Page 4), your first goal is to "Present a mathematical model of IP". Should we consider this as a goal statement? Calculation in GS2 and GS3 seems ok, but presentation can be considered as a goal?

**Comment by MinMah23** [comment]
@DeeshaPatel
I see what you are telling, I'm not sure about it and somehow agree with you. however, let me ask @smiths.

**Comment by MinMah23** [comment]
I've deleted it in commit 4d129a5.

**Comment by smiths** [comment]
I agree that presenting a mathematical model is not a goal statement in the way that we use goal statement in our template.  The "goal" of the SRS itself is to present the mathematical model.  The goal of the software is to take inputs and produce outputs.
