### ISSUE TITLE
Issues with Assumptions 

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#9]
@MinMah23 

In 4.2.1 Assumptions (Page 4), I found some issues with it. 

- Each assumption should atomic. 
- cos(θ)isequalto1 - why it's combined? 
- You should mention the references of the Assumptions.

**Comment by MinMah23** [comment]
@DeeshaPatel 
It's not combined, I just explain why cos(θ)isequalto1, because it is small, So, maybe it's better to change the assumption that θ is small and as a result sin , cos will be constants. I will correct it. Thanks
